export const ADD_NOMINATION = "ADD_NOMINATION";
export const REMOVE_NOMINATION = "REMOVE_NOMINATION";

export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";